project:
  type: website
  output-dir: docs

website:
  title: "Christian Rodríguez Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CristianRod21
format:
  html:
    theme: cosmo
    css: styles.css



